### ISSUE TITLE
X-Frame-Options is set to sameorigin

### ISSUE THREAD

**Issue by goessensj** [hassio-addons/addon-uptime-kuma#101] opened 2023-08-27 13:38 UTC
# Problem/Motivation

Uptime Kuma not possible to display in iframe

## Expected behavior

Web app shown correctly in iframe

## Actual behavior

https://url refused to connect

## Steps to reproduce

Add uptimekuma as an iframe in Home Assistant, fails to load because 'X-Frame-Options' is set to 'sameorigin':
Google Chrome: `Refused to display '<URL>' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

## Proposed changes

Fix in original docker image: Set env variable "UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true"

**Comment by frenck** [comment] 2023-08-28 07:09
Duplicate of many others. Please use the search before creating issues. Thx!

**Closed** 2023-08-28 07:10 UTC

**Comment by goessensj** [comment] 2023-08-28 08:24
Make a positive difference every single day. Bye!

**Comment by frenck** [comment] 2023-08-28 08:27
Lol I get the irony you are trying to bring across, yet… I do think that is makes it harsher than it really is.

Anyways 👋🍻

**Comment by frenck** [comment] 2023-08-28 08:34
It wasn’t meant arrogant at all, you made it that way. I just referenced it has been handled and requested before, a simple search would have give you that information 🤷‍♂️

As a matter of fact, I am on 2000m+ height hiking with my family right now and even take the a moment to handle things on mobile during A break… and that makes me a prick? Just wow.

You just made my day, thanks!
