### ISSUE TITLE
Update Uptime Kuma to 1.20.1

### ISSUE THREAD

**Issue by OneYellowLemon** [hassio-addons/addon-uptime-kuma#45] opened 2023-02-21 23:22 UTC
[Uptime Kuma 1.20.1](https://github.com/louislam/uptime-kuma/releases/tag/1.20.1) has been released, and this image should be updated.

**Comment by frenck** [comment] 2023-02-22 08:46
Cool.

Closing this as it is a feature request and not a bug.

../Frenck

**Closed by frenck** 2023-02-22 08:46 UTC
